FROM eclipse-temurin:17.0.9_9-jre-alpine

WORKDIR /app

COPY target/*.jar opt/app/hotel-backend-0.0.1-SNAPSHOT.jar

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

EXPOSE 8080

CMD java -jar /opt/app/hotel-backend-0. 0.1-SNAPSHOT.jar